package patterns

import (
	"strings"

	"github.com/inovacc/unravel-oss/pkg/java/decompiler/ast/stmt"
)

// isEnumSyntheticBody checks whether a method body consists entirely of
// synthetic enum statements generated by javac. It detects:
//
//   - $VALUES array assignment (static initializer)
//   - values() synthetic method body (return $VALUES.clone())
//   - valueOf(String) synthetic method body (return Enum.valueOf(...))
//
// Returns true if the entire method body is synthetic and should be omitted.
func isEnumSyntheticBody(stmts []stmt.Statement) bool {
	if len(stmts) == 0 {
		return false
	}

	// Check each statement: every one must be recognizably synthetic.
	for _, s := range stmts {
		if !isEnumSyntheticStatement(s) {
			return false
		}
	}

	return true
}

// isEnumSyntheticStatement returns true if a single statement is part of a
// synthetic enum method body.
func isEnumSyntheticStatement(s stmt.Statement) bool {
	text := s.String()

	// Pattern 1: return (ClassName[])$VALUES.clone()
	// This is the synthetic values() method.
	if s.Kind() == stmt.KindReturn && strings.Contains(text, "$VALUES") && strings.Contains(text, "clone()") {
		return true
	}

	// Pattern 2: return (ClassName)Enum.valueOf(ClassName.class, name)
	// This is the synthetic valueOf(String) method.
	if s.Kind() == stmt.KindReturn && strings.Contains(text, "Enum.valueOf") {
		return true
	}

	// Pattern 3: $VALUES = new ClassName[] { ... }  (static initializer assignment)
	if s.Kind() == stmt.KindAssignment || s.Kind() == stmt.KindExpression {
		if strings.Contains(text, "$VALUES") {
			return true
		}
	}

	// Pattern 4: ENUM$VALUES assignment (alternative compiler naming)
	if s.Kind() == stmt.KindAssignment || s.Kind() == stmt.KindExpression {
		if strings.Contains(text, "ENUM$VALUES") {
			return true
		}
	}

	// Pattern 5: new ClassName("NAME", ordinal) enum constant initialization
	// in static initializer blocks
	if s.Kind() == stmt.KindAssignment || s.Kind() == stmt.KindExpression {
		if containsEnumFieldRef(text) {
			return true
		}
	}

	// Recurse into blocks: a synthetic method body may be wrapped in a Block.
	if blk, ok := s.(*stmt.Block); ok {
		return isEnumSyntheticBody(blk.Stmts)
	}

	return false
}

// containsEnumFieldRef returns true if text references a known synthetic enum
// field pattern as part of an enum constant constructor call. This catches
// assignments like: NAME = new MyEnum("NAME", 0)
func containsEnumFieldRef(text string) bool {
	// Enum constant init in static blocks typically references $VALUES
	// or ENUM$VALUES. Individual constant assignments don't have a simple
	// string-based marker, so we only catch the aggregated forms here.
	return false
}

// isSyntheticEnumField returns true if a field name is a compiler-generated
// enum field. Javac and ecj use several naming conventions:
//
//   - $VALUES — standard javac enum values array
//   - ENUM$VALUES — alternative javac naming
//   - $SWITCH_TABLE$... — switch map for enum switches (javac)
//   - $SwitchMap$... — switch map for enum switches (ecj/Eclipse compiler)
func isSyntheticEnumField(name string) bool {
	if name == "$VALUES" || name == "ENUM$VALUES" {
		return true
	}

	if strings.HasPrefix(name, "$SWITCH_TABLE$") {
		return true
	}

	if strings.HasPrefix(name, "$SwitchMap$") {
		return true
	}

	return false
}
