/*
Copyright (c) 2026 Security Research
*/
package forensic

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RunSingle generates a forensic report for a single app from its teardown directory.
func RunSingle(appDir string) (*Report, error) {
	// Find the UUID teardown subdirectory
	teardownDir, err := findTeardownDir(appDir)
	if err != nil {
		return nil, fmt.Errorf("no teardown data in %s: %w", appDir, err)
	}

	appID := filepath.Base(appDir)
	report := &Report{
		AppID:    appID,
		Findings: []Finding{},
	}

	// Load each analysis result from disk
	loadCert(teardownDir, report)
	loadManifest(teardownDir, report)
	loadNetwork(teardownDir, report)
	loadSecrets(teardownDir, report)
	loadTelemetry(teardownDir, report)
	loadMetadata(teardownDir, report)

	// Generate curl replay scripts from network data
	report.CurlScripts = generateCurlScripts(report)

	// Compute risk score
	report.RiskScore, report.RiskLevel = computeRisk(report)

	// Generate forensic findings
	report.Findings = generateFindings(report)

	return report, nil
}

// RunBatch generates forensic reports for all apps in a teardown base directory.
func RunBatch(baseDir string, opts Options) (*BatchReport, error) {
	entries, err := os.ReadDir(baseDir)
	if err != nil {
		return nil, fmt.Errorf("read teardown dir: %w", err)
	}

	batch := &BatchReport{
		Apps:        []Report{},
		DomainIndex: map[string][]string{},
		SDKIndex:    map[string][]string{},
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if strings.HasPrefix(entry.Name(), "_") {
			continue
		}

		appDir := filepath.Join(baseDir, entry.Name())
		report, err := RunSingle(appDir)
		if err != nil {
			if opts.Verbose {
				fmt.Fprintf(os.Stderr, "SKIP %s: %v\n", entry.Name(), err)
			}
			continue
		}

		batch.Apps = append(batch.Apps, *report)
		batch.TotalApps++

		// Build domain index
		if report.Network != nil {
			for _, d := range report.Network.Domains {
				batch.DomainIndex[d] = append(batch.DomainIndex[d], report.AppID)
			}
		}

		// Build SDK index
		if report.Telemetry != nil {
			for _, sdk := range report.Telemetry.SDKs {
				batch.SDKIndex[sdk.Name] = append(batch.SDKIndex[sdk.Name], report.AppID)
			}
		}
	}

	// Sort by risk score descending
	sort.Slice(batch.Apps, func(i, j int) bool {
		return batch.Apps[i].RiskScore > batch.Apps[j].RiskScore
	})

	// Top 20 risks
	topN := min(len(batch.Apps), 20)
	batch.TopRisks = batch.Apps[:topN]

	return batch, nil
}

// WriteReport writes a forensic report to disk as markdown + curl scripts.
func WriteReport(report *Report, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// Write main report markdown
	md := renderMarkdown(report)
	if err := os.WriteFile(filepath.Join(outDir, "FORENSIC_REPORT.md"), []byte(md), 0o644); err != nil {
		return err
	}

	// Write curl scripts
	if len(report.CurlScripts) > 0 {
		curlDir := filepath.Join(outDir, "curl")
		if err := os.MkdirAll(curlDir, 0o755); err != nil {
			return err
		}

		// Write individual curl scripts by category
		catScripts := map[string][]CurlScript{}
		for _, cs := range report.CurlScripts {
			catScripts[cs.Category] = append(catScripts[cs.Category], cs)
		}

		for cat, scripts := range catScripts {
			var sb strings.Builder
			sb.WriteString(fmt.Sprintf("#!/usr/bin/env bash\n"))
			sb.WriteString(fmt.Sprintf("# Forensic API Replay: %s — %s endpoints\n", report.AppID, cat))
			sb.WriteString(fmt.Sprintf("# Generated by unravel forensic\n"))
			sb.WriteString(fmt.Sprintf("# Category: %s | Scripts: %d\n\n", cat, len(scripts)))

			for i, cs := range scripts {
				sb.WriteString(fmt.Sprintf("# [%d] %s\n", i+1, cs.Description))
				sb.WriteString(fmt.Sprintf("# Risk: %s\n", cs.Risk))
				sb.WriteString(cs.Command)
				sb.WriteString("\n\n")
			}

			fname := fmt.Sprintf("%s.sh", cat)
			_ = os.WriteFile(filepath.Join(curlDir, fname), []byte(sb.String()), 0o755)
		}

		// Write all-in-one curl script
		var all strings.Builder
		all.WriteString("#!/usr/bin/env bash\n")
		all.WriteString(fmt.Sprintf("# Forensic API Replay: %s — ALL endpoints\n", report.AppID))
		all.WriteString(fmt.Sprintf("# Total scripts: %d\n\n", len(report.CurlScripts)))
		all.WriteString("set -euo pipefail\n\n")

		for i, cs := range report.CurlScripts {
			all.WriteString(fmt.Sprintf("echo \"[%d/%d] %s (%s)\"\n", i+1, len(report.CurlScripts), cs.Name, cs.Category))
			all.WriteString(cs.Command)
			all.WriteString("\necho \"\"\n\n")
		}

		_ = os.WriteFile(filepath.Join(curlDir, "replay-all.sh"), []byte(all.String()), 0o755)
	}

	// Write JSON report
	jsonData, _ := json.MarshalIndent(report, "", "  ")
	_ = os.WriteFile(filepath.Join(outDir, "forensic.json"), jsonData, 0o644)

	return nil
}

// WriteBatchReport writes the batch summary + per-app reports.
func WriteBatchReport(batch *BatchReport, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// Per-app reports
	for _, app := range batch.Apps {
		appOut := filepath.Join(outDir, app.AppID)
		if err := WriteReport(&app, appOut); err != nil {
			fmt.Fprintf(os.Stderr, "WARN: %s: %v\n", app.AppID, err)
		}
	}

	// Batch summary markdown
	summary := renderBatchSummary(batch)
	_ = os.WriteFile(filepath.Join(outDir, "FORENSIC_SUMMARY.md"), []byte(summary), 0o644)

	// Batch JSON
	jsonData, _ := json.MarshalIndent(batch, "", "  ")
	_ = os.WriteFile(filepath.Join(outDir, "forensic_batch.json"), jsonData, 0o644)

	// Domain index
	domainMD := renderDomainIndex(batch)
	_ = os.WriteFile(filepath.Join(outDir, "DOMAIN_INDEX.md"), []byte(domainMD), 0o644)

	// SDK index
	sdkMD := renderSDKIndex(batch)
	_ = os.WriteFile(filepath.Join(outDir, "SDK_INDEX.md"), []byte(sdkMD), 0o644)

	return nil
}

// findTeardownDir locates the UUID subdirectory containing manifest.json.
func findTeardownDir(appDir string) (string, error) {
	entries, err := os.ReadDir(appDir)
	if err != nil {
		return "", err
	}

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		candidate := filepath.Join(appDir, e.Name(), "manifest.json")
		if _, err := os.Stat(candidate); err == nil {
			return filepath.Join(appDir, e.Name()), nil
		}
	}

	return "", fmt.Errorf("no manifest.json found")
}

// loadJSON loads a JSON file from the teardown directory into the target.
func loadJSON(dir, filename string, target any) error {
	path := filepath.Join(dir, filename)
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, target)
}

// classifyEndpoint determines the category of an API endpoint.
func classifyEndpoint(ep APIEndpoint) string {
	u := strings.ToLower(ep.URL)
	path := strings.ToLower(ep.Path)
	host := strings.ToLower(ep.Host)

	switch {
	case strings.Contains(path, "/oauth") || strings.Contains(path, "/auth") ||
		strings.Contains(path, "/login") || strings.Contains(path, "/token"):
		return "auth"
	case strings.Contains(path, "/api/") || strings.Contains(path, "/v1/") ||
		strings.Contains(path, "/v2/") || strings.Contains(path, "/v3/") ||
		strings.Contains(path, "/graphql"):
		return "api"
	case strings.Contains(host, "analytics") || strings.Contains(host, "tracking") ||
		strings.Contains(host, "telemetry") || strings.Contains(u, "collect") ||
		strings.Contains(host, "amplitude") || strings.Contains(host, "mixpanel") ||
		strings.Contains(host, "segment"):
		return "analytics"
	case strings.Contains(host, "firebase") || strings.Contains(host, "fcm") ||
		strings.Contains(path, "/push") || strings.Contains(path, "/notification"):
		return "push"
	case strings.Contains(host, "cdn") || strings.Contains(host, "static") ||
		strings.Contains(host, "cloudfront") || strings.Contains(host, "akamai"):
		return "cdn"
	case strings.Contains(path, "/webhook") || strings.Contains(path, "/callback"):
		return "webhook"
	case strings.Contains(path, "/pay") || strings.Contains(path, "/checkout") ||
		strings.Contains(path, "/purchase") || strings.Contains(host, "stripe") ||
		strings.Contains(host, "paypal"):
		return "payment"
	case strings.Contains(host, "sentry") || strings.Contains(host, "crashlytics") ||
		strings.Contains(host, "bugsnag"):
		return "crash_reporting"
	default:
		return "other"
	}
}

// classifyRisk returns a risk level for a curl script based on endpoint category.
func classifyRisk(category string, ep APIEndpoint) string {
	switch category {
	case "auth":
		return "high"
	case "payment":
		return "high"
	case "api":
		return "medium"
	case "webhook":
		return "medium"
	case "analytics":
		return "low"
	case "push":
		return "low"
	case "cdn":
		return "info"
	default:
		return "info"
	}
}

// isAPIEndpoint filters out non-API URLs (docs, help pages, static assets).
func isAPIEndpoint(ep APIEndpoint) bool {
	host := strings.ToLower(ep.Host)
	path := strings.ToLower(ep.Path)
	u := strings.ToLower(ep.URL)

	// Skip XML namespace URIs
	if strings.Contains(host, "xmlpull.org") || strings.Contains(host, "xml.org") ||
		strings.Contains(host, "w3.org") || strings.Contains(host, "xmlns") ||
		strings.Contains(host, "javax.xml") || strings.Contains(host, "schemas.") {
		return false
	}

	// Skip documentation/help URLs
	if strings.Contains(path, "/help") || strings.Contains(path, "/support") ||
		strings.Contains(path, "/docs/") || strings.Contains(path, "/faq") ||
		strings.Contains(path, "/terms") || strings.Contains(path, "/privacy") ||
		strings.Contains(path, "/policy") || strings.Contains(path, "/legal") ||
		strings.Contains(path, "/about") {
		return false
	}

	// Skip social media share links
	if strings.Contains(u, "play.google.com") || strings.Contains(u, "apps.apple.com") ||
		strings.Contains(u, "itunes.apple.com") {
		return false
	}

	// Skip empty or very short paths (usually just the domain root)
	if ep.Path == "" || ep.Path == "/" {
		return false
	}

	// Must have a valid host
	return ep.Host != "" && len(ep.Host) > 3
}

// generateCurlScripts creates curl commands for replaying discovered API endpoints.
func generateCurlScripts(report *Report) []CurlScript {
	if report.Network == nil || len(report.Network.APIEndpoints) == 0 {
		return nil
	}

	var scripts []CurlScript
	seen := map[string]bool{}

	for _, ep := range report.Network.APIEndpoints {
		if !isAPIEndpoint(ep) {
			continue
		}

		// Dedup by host+path
		key := ep.Host + ep.Path
		if seen[key] {
			continue
		}
		seen[key] = true

		cat := classifyEndpoint(ep)
		risk := classifyRisk(cat, ep)
		method := ep.Method
		if method == "" {
			method = "GET"
		}

		// Build curl command
		cmd := buildCurl(ep, method, report)

		scripts = append(scripts, CurlScript{
			Name:        fmt.Sprintf("%s %s", method, ep.Path),
			Description: fmt.Sprintf("%s → %s%s", cat, ep.Host, ep.Path),
			Category:    cat,
			Command:     cmd,
			URL:         ep.URL,
			Method:      method,
			Risk:        risk,
		})
	}

	// Sort by category then risk
	sort.Slice(scripts, func(i, j int) bool {
		if scripts[i].Category != scripts[j].Category {
			return scripts[i].Category < scripts[j].Category
		}
		return riskOrder(scripts[i].Risk) > riskOrder(scripts[j].Risk)
	})

	return scripts
}

func riskOrder(r string) int {
	switch r {
	case "critical":
		return 4
	case "high":
		return 3
	case "medium":
		return 2
	case "low":
		return 1
	default:
		return 0
	}
}

// buildCurl generates a curl command string for an endpoint.
func buildCurl(ep APIEndpoint, method string, report *Report) string {
	var parts []string
	parts = append(parts, "curl")

	// Method
	if method != "GET" {
		parts = append(parts, "-X", method)
	}

	// Verbose + follow redirects
	parts = append(parts, "-v", "-L")

	// Standard headers that apps typically send
	parts = append(parts, "-H", fmt.Sprintf("'User-Agent: %s/1.0 (Android)'", report.AppID))
	parts = append(parts, "-H", "'Accept: application/json'")
	parts = append(parts, "-H", "'Accept-Language: en-US,pt-BR;q=0.9'")

	// Auth placeholder for auth endpoints
	cat := classifyEndpoint(ep)
	if cat == "auth" || cat == "api" || cat == "payment" {
		parts = append(parts, "-H", "'Authorization: Bearer <TOKEN>'")
	}

	// Content-Type for POST-like endpoints
	if method == "POST" || method == "PUT" || method == "PATCH" {
		parts = append(parts, "-H", "'Content-Type: application/json'")
		parts = append(parts, "-d", "'{}'")
	}

	// Custom headers from discovery
	for k, v := range ep.Headers {
		parts = append(parts, "-H", fmt.Sprintf("'%s: %s'", k, v))
	}

	// URL (escape special chars)
	cleanURL := ep.URL
	if u, err := url.Parse(ep.URL); err == nil {
		cleanURL = u.String()
	}
	parts = append(parts, fmt.Sprintf("'%s'", cleanURL))

	return strings.Join(parts, " \\\n  ")
}

// computeRisk calculates an overall risk score (0-100).
func computeRisk(report *Report) (int, string) {
	score := 0

	// Secrets
	if report.Secrets != nil {
		score += min(report.Secrets.HighConfidence*5, 30)
	}

	// Manifest issues
	if report.Manifest != nil {
		if report.Manifest.Debuggable {
			score += 15
		}
		if report.Manifest.CleartextOK {
			score += 10
		}
		if report.Manifest.AllowBackup {
			score += 5
		}
		score += min(len(report.Manifest.DangerousPerm)*2, 20)
	}

	// Network
	if report.Network != nil {
		if report.Network.HasCleartext {
			score += 10
		}
		if !report.Network.HasCertPinning {
			score += 5
		}
	}

	// Telemetry & stealth
	if report.Telemetry != nil {
		for _, sf := range report.Telemetry.StealthFeatures {
			if sf.Risk == "high" {
				score += 10
			}
		}
	}

	// Certificate
	if report.Certificate != nil {
		if report.Certificate.Expired {
			score += 10
		}
	}

	if score > 100 {
		score = 100
	}

	level := "low"
	switch {
	case score >= 70:
		level = "critical"
	case score >= 50:
		level = "high"
	case score >= 30:
		level = "medium"
	}

	return score, level
}
