/*
Copyright (c) 2026 Security Research
*/
package scorecard

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/inovacc/unravel-oss/pkg/android/secret"
	"github.com/inovacc/unravel-oss/pkg/dissect"
	elecapp "github.com/inovacc/unravel-oss/pkg/electron/app"
	"github.com/inovacc/unravel-oss/pkg/electron/binary"
	"github.com/inovacc/unravel-oss/pkg/msix"
)

func TestCryptoScorer(t *testing.T) {
	cases := []struct {
		name string
		r    *dissect.DissectResult
		want int
	}{
		{"nil", nil, 0},
		{"empty", &dissect.DissectResult{}, 0},
		{"two_indicators", &dissect.DissectResult{
			JSAnalysis: &dissect.JSAnalysisResult{
				Indicators: []string{"AES-GCM mode", "WebCrypto.subtle"},
			},
		}, 24}, // +12 aes +12 webcrypto
		{"all_six_indicators_no_bin", &dissect.DissectResult{
			JSAnalysis: &dissect.JSAnalysisResult{
				Indicators: []string{"aes", "webcrypto", "libsignal", "curve25519", "kdf", "protobuf"},
			},
		}, 72}, // 6*12
		{"six_plus_bin_caps", &dissect.DissectResult{
			JSAnalysis: &dissect.JSAnalysisResult{
				Indicators: []string{"aes", "webcrypto", "libsignal", "curve25519", "kdf", "protobuf"},
			},
			AppAnalysis: &elecapp.Result{
				Binaries: []binary.Info{{SampleStrings: []string{"libsignal_protocol"}}},
			},
		}, 90}, // 72 + 18 = 90 cap
		{"floor_70_via_secrets", &dissect.DissectResult{
			Secrets: &secret.ScanResult{TotalFindings: 60},
		}, 70},
		{"low_score_below_floor_lifts", &dissect.DissectResult{
			JSAnalysis: &dissect.JSAnalysisResult{Indicators: []string{"aes"}}, // 12
			Secrets:    &secret.ScanResult{TotalFindings: 60},
		}, 70},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := cryptoScorer{}.Score(tc.r, nil)
			if got.Score != tc.want {
				t.Errorf("Score = %d, want %d", got.Score, tc.want)
			}
		})
	}
}

// TestCryptoScorerCrossPlatform — B3 of P64. Runs scanPEImportsForCrypto
// against the committed minimal-valid PE fixture (testdata/synthetic_pe.bin)
// generated by internal/devtools/gen_synthetic_pe. The fixture imports
// Crypt32.dll!CryptAcquireContextW and Bcrypt.dll!BCryptOpenAlgorithmProvider.
//
// IMPORTANT: NO t.Skipf for any GOOS — debug/pe is pure-Go stdlib, the parser
// must work on Linux, macOS, and Windows alike. This test enforces that
// invariant.
func TestCryptoScorerCrossPlatform(t *testing.T) {
	matches, err := scanPEImportsForCrypto("testdata/synthetic_pe.bin")
	if err != nil {
		t.Fatalf("scanPEImportsForCrypto: %v", err)
	}
	want := map[string]bool{"crypt32.dll": false, "bcrypt.dll": false}
	for _, m := range matches {
		if _, ok := want[m]; ok {
			want[m] = true
		}
	}
	for k, found := range want {
		if !found {
			t.Errorf("missing crypto DLL match: %s (got %v)", k, matches)
		}
	}
}

// TestCryptoScorer_UWPInstallDir exercises the SCRG-04 UWP branch end-to-end.
// Synthesizes an install-dir layout pointing at the committed synthetic_pe.bin
// fixture. Asserts non-empty Evidence with typed-field Citation
// (MSIXInfo.Files[i].Name) plus JS-reference Evidence with JSAnalysis.File.
func TestCryptoScorer_UWPInstallDir(t *testing.T) {
	// Stage the synthetic PE inside a temp install-dir as "Native.dll" so
	// the relative entry name in MSIXInfo.Files joins to the real file.
	dir := t.TempDir()
	srcBytes, err := os.ReadFile("testdata/synthetic_pe.bin")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "Native.dll"), srcBytes, 0o644); err != nil {
		t.Fatalf("stage fixture: %v", err)
	}

	r := &dissect.DissectResult{
		SourcePath: dir,
		MSIXInfo: &msix.InfoResult{
			Files: []msix.FileEntry{
				{Name: "Native.dll", Size: int64(len(srcBytes))},
			},
		},
		JSAnalysis: &dissect.JSAnalysisResult{
			File:           "App/app.js",
			DangerousCalls: []string{"libsignal-protocol.encrypt(...)"},
		},
	}
	got := cryptoScorer{}.Score(r, nil)
	if got.Score == 0 {
		t.Fatalf("UWP install-dir Score = 0; want non-zero (got %+v)", got)
	}
	if len(got.Evidence) == 0 {
		t.Fatal("UWP install-dir Evidence empty")
	}
	for i, ev := range got.Evidence {
		if ev.Citation == nil {
			t.Errorf("Evidence[%d].Citation is nil", i)
			continue
		}
		if ev.Citation.File == r.SourcePath {
			t.Errorf("Evidence[%d].Citation.File leaked r.SourcePath", i)
		}
	}
}

// TestCryptoScorer_UWPNilSafe — UWP guard suppresses branch when MSIXInfo
// has no PE entries OR when Electron AppAnalysis is also present (legacy
// curve takes precedence in that case).
func TestCryptoScorer_UWPNilSafe(t *testing.T) {
	cases := []struct {
		name string
		r    *dissect.DissectResult
	}{
		{"no_pe_entries", &dissect.DissectResult{
			MSIXInfo: &msix.InfoResult{Files: []msix.FileEntry{{Name: "asset.png"}}},
		}},
		{"electron_present_skips_uwp", &dissect.DissectResult{
			MSIXInfo:    &msix.InfoResult{Files: []msix.FileEntry{{Name: "x.dll"}}},
			AppAnalysis: &elecapp.Result{Binaries: []binary.Info{{Name: "main"}}},
		}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// must not panic
			_ = cryptoScorer{}.Score(tc.r, nil)
		})
	}
}
